import = [ "~/.config/alacritty/themes/themes/catppuccin_frappe.toml" ]

[font.normal]
family = "UbuntuMono Nerd Font"

[env]
TERM = "xterm-256color"

[font]
size = 15

[window.padding]
x = 7
y = 0

[window]
opacity = 0.80

[selection]
save_to_clipboard = true

[cursor.style]
shape = "Beam"
blinking = "On"